docs_dir:           "docs/"

edit_uri:           "tree/main/docs"

repo_name:          "T4-Notes"
repo_url:           "https://github.com/Divy1211/T4-Notes/"

site_author:        "Divy Chandra"
site_description:   "Personal Notes"
site_name:          "T4 Notes 2022"
site_url:           "https://divy1211.github.io/T4-Notes/"

use_directory_urls: true

nav:
  # - About:                                  
  # -                                         "index.md"
  - Algorithms:
    - Notes:
      - Algorithms:                         "algo/notes/w1/algos.md"
      - Document Distance:                  "algo/notes/w1/docdist.md"
      - Sorting & Solving Recurrances:      "algo/notes/w2/sort_recur.md"
      - Master Theorem & Peak Finding:      "algo/notes/w2/master_peak.md"
      - Heaps:                              "algo/notes/w3/heaps.md"
      - Heap Operations:                    "algo/notes/w3/heap_ops.md"
      - Binary Search Trees:                "algo/notes/w4/bst.md"
      - AVL Trees:                          "algo/notes/w4/avl.md"
      - Hashing:                            "algo/notes/w5/hashing.md"
      - Graphs:                             "algo/notes/w6/graphs.md"
      - Shortest Path:                      "algo/notes/w9/shortest_path.md"
      - Bellman Ford:                       "algo/notes/w9/bellman_ford.md"
      - Dijkstra's Algorithm:               "algo/notes/w9/dijkstras.md"
      - Dynamic Programming:                "algo/notes/w10/dp.md"
      - P and NP:                           "algo/notes/w12/pnp.md"
    - Deadlines:                            "algo/deadlines.md"
    - Homework Sets:
      - HW Set 1:                           "algo/hwsets/hwset1.md"
      - HW Set 2:                           "algo/hwsets/hwset2.md"
      - HW Set 3:                           "algo/hwsets/hwset3.md"
      - HW Set 4:                           "algo/hwsets/hwset4.md"
      - HW Set 5:                           "algo/hwsets/hwset5.md"
      - HW Set 6:                           "algo/hwsets/hwset6.md"
      - PSet 1:                             "algo/psets/pset1.md"
      - PSet 2:                             "algo/psets/pset2.md"
    - Info:                                 "algo/to_know.md"
  - Computation Structures:
    - Notes:
      - Basics of Information:              "comp_structs/notes/w1/basics_of_info.md"
      - Digital Abstraction:                "comp_structs/notes/w1/digital_abstraction.md"
      - CMOS Tech:                          "comp_structs/notes/w2/cmos.md"
      - Logic Synthesis:                    "comp_structs/notes/w2/logic_synth.md"
      - Sequential Logic & Sync:            "comp_structs/notes/w3/seq_sync.md"
      - Finite State Machines:              "comp_structs/notes/w3/fsm.md"
      - Turing Machines & Programmability:  "comp_structs/notes/w4/turing.md"
      - Designing an Instruction Set:       "comp_structs/notes/w4/instruct.md"
      - Building The Beta CPU:              "comp_structs/notes/w5/beta_cpu.md"
      - Beta Components:                    "comp_structs/notes/w5/beta_components.md"
      - Assemblers & Compilers:             "comp_structs/notes/w5/assembly.md"
      - Stacks and Procedures:              "comp_structs/notes/w9/stacks.md"
      - Memory Hierarchy:                   "comp_structs/notes/w10/mem_hier.md"
      - Cache Design Issues:                "comp_structs/notes/w10/cache.md"
      - Virtual Memory:                     "comp_structs/notes/w11/vmem.md"
      - Virtual Machine:                    "comp_structs/notes/w11/vm.md"
      - System Calls:                       "comp_structs/notes/w13/syscalls.md"
      - Important Concepts:                 "comp_structs/notes/w13/imp.md"
    - Deadlines:                            "comp_structs/deadlines.md"
    - Info:                                 "comp_structs/to_know.md"
  - Infosys and Programming:
    - Notes:                                "infosys/notes/w1.md"
    - 1D:                                   
      - App Framework:                      "infosys/1D/app_framew.md"
    - Deadlines:                            "infosys/deadlines.md"
    - Info:                                 "infosys/to_know.md"
  - HASS Digital Humanities:
    - Notes:                                "hass/notes/w1.md"
    - Deadlines:                            "hass/deadlines.md"
    - Info:                                 "hass/to_know.md"

markdown_extensions:
  - attr_list
  - admonition                # Create not and warning boxes        https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - md_in_html
  - pymdownx.caret            # Handling sub- and superscripts      https://facelessuser.github.io/pymdown-extensions/extensions/caret/
  - pymdownx.critic           #                                     https://facelessuser.github.io/pymdown-extensions/extensions/critic/
  - pymdownx.details          # Collapsable elements                https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.inlinehilite     # Inline code highlighting            https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
  - pymdownx.keys             # Add styling keyboard keys           https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.mark             # Highlighting of text                https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.smartsymbols     # Creating special characters         https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.snippets         #                                     https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.superfences
  - pymdownx.tabbed           # Tabs                                https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.tasklist         #                                     https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
  - pymdownx.tilde            # Strikethrough of text               https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.arithmatex:      # Preserve LaTeX math equations       https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
      generic: true
  - pymdownx.emoji:           # Emojis                              https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
      emoji_index:     !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:       # Highlighting code blocks            https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
      linenums:     true
      use_pygments: true
  - pymdownx.superfences:     # Complicated code fences             https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
      custom_fences:
        - name:   mermaid
          class:  mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:        # Creating Check-able tasklist        https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
      custom_checkbox:    true
      clickable_checkbox: true
  - toc:
      permalink: true
plugins:
  - search:
      lang: en
      separator: '[\s\-\.\_]+'

theme:
  # favicon:
  language: en
  name: material
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  font:
    text: Times New Roman
    code: Consolas
  icon:
    logo: octicons/file-code-24
    admonition:
      abstract: octicons/checklist-16
      bug:      octicons/bug-16
      danger:   octicons/zap-16
      example:  octicons/beaker-16
      failure:  octicons/x-circle-16
      info:     octicons/info-16
      note:     octicons/tag-16
      success:  octicons/check-16
      tip:      octicons/squirrel-16
      question: octicons/question-16
      quote:    octicons/quote-16
      warning:  octicons/alert-16
  palette:
    scheme:  slate
    primary: red
    accent:  red
extra_javascript:
  - js/maths.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - ./css/style.css